[package]
name = "cardinal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-executor = "1.4.1"
wgpu = "0.12.0"
winit = "0.26.1"
tokio = { version = "1", features = ["full"] }